# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CAICU 2023
email: caicu.uy@gmail.com
description: 1er Congreso Académico Interdisciplinario sobre Carnaval Uruguayo
subdescription: Montevideo - Septiembre 2023
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://caicu2023.github.io" # the base hostname & protocol for your site

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: caicu2023
twitter_username: caicu.uy
facebook_URL: caicu.uy
instagram_username: caicu.uy

# Build settings
markdown: kramdown
